hideType = "RELOADING"
rgbProgress = false
showIn = "ALL"
type = "PROGRESS"
reloadText = "Edit in config!"
resetResources = false
reInitScreen = true
earlyPackStatus = "SEND"
animationSpeed = 1000.0
aprilFool = "ON_APRIL"
